receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Scrape delle metriche 
  prometheus:
    config:
      scrape_configs:
        - job_name: "app-python"
          scrape_interval: 5s
          static_configs:
            - targets: ["app-python:5000"]

processors:
  batch: {}
  memory_limiter:
    check_interval: 2s
    limit_mib: 256
    spike_limit_mib: 128

exporters:
  #Prometheus (porta 9464)
  prometheus:
    endpoint: "0.0.0.0:9464"

  #  Jaeger 
  #  OTLP gRPC sulla 4317.
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  #  Tempo exporter:
  # otlp/tempo:
  #   endpoint: "tempo:4317"
  #   tls:
  #     insecure: true

service:
  pipelines:
    # Prometheus exporter
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheus]

    #  Jaeger exporter
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger]
      # exporters: [otlp/jaeger, otlp/tempo]