---
    - name: Ottieni crumb e salva cookie
      shell: |
        rm -f cookies.txt
        crumb_json=$(curl -c cookies.txt -s -u {{ jenkins_user }}:{{ jenkins_password }} \
          "{{ jenkins_url }}/crumbIssuer/api/json")
        echo "$crumb_json" > crumb.json

    - name: Estrai crumb e field name
      shell: |
        crumb=$(jq -r .crumb crumb.json)
        crumb_field=$(jq -r .crumbRequestField crumb.json)
        echo "$crumb" > crumb.txt
        echo "$crumb_field" > crumb_field.txt

    - name: Genera nuovo API Token
      shell: |
        crumb=$(cat crumb.txt)
        crumb_field=$(cat crumb_field.txt)
        token_json=$(curl -b cookies.txt -s -X POST -u {{ jenkins_user }}:{{ jenkins_password }} \
          -H "$crumb_field: $crumb" \
          -d "newTokenName=my-new-token" \
          "{{ jenkins_url }}/me/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken")
        echo "$token_json" > token.json

    - name: Estrai valore API Token
      shell: |
        jq -r .data.tokenValue token.json > api_token.txt

    - name: Crea nuovo agent node
      shell: |
        crumb=$(cat crumb.txt)
        crumb_field=$(cat crumb_field.txt)
        api_token=$(cat api_token.txt)
        curl -b cookies.txt -s -X POST -u {{ jenkins_user }}:$api_token \
          -H "$crumb_field: $crumb" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "name={{ agent_name }}" \
          --data-urlencode "type=hudson.slaves.DumbSlave" \
          --data-urlencode 'json={"name":"{{ agent_name }}","nodeDescription":"Ansible created agent","numExecutors":"1","remoteFS":"{{ agent_work_dir }}","labelString":"","mode":"EXCLUSIVE"}' \
          --data-urlencode "Submit=OK" \
          "{{ jenkins_url }}/computer/doCreateItem"

    - name: Recupera secret dal JNLP
      shell: |
        api_token=$(cat api_token.txt)
        jnlp=$(curl -s -u {{ jenkins_user }}:$api_token "{{ jenkins_url }}/computer/{{ agent_name }}/jenkins-agent.jnlp")
        echo "$jnlp" > jnlp.xml
        grep -oPm1 "(?<=<argument>)[a-z0-9]{32,}(?=</argument>)" jnlp.xml > agent_secret.txt

    - name: Avvia container agent
      shell: |
        agent_secret=$(cat agent_secret.txt)
        docker rm -f {{ agent_container_name }} || true
        docker run -d --name {{ agent_container_name }} \
          --restart unless-stopped \
          jenkins/inbound-agent \
          -url {{ jenkins_url }} \
          -name {{ agent_name }} \
          -secret $agent_secret

    - name: Mostra log dell'agent
      shell: |
        sleep 10
        docker logs {{ agent_container_name }}
