---
- name: otel-lab 
  hosts: all
  become: true

  vars:
    project_root: "/home/vagrant/otel-lab"
    compose_dir: "{{ project_root }}/compose"
    open_ports:
      - 5000   # app
      - 9464   # collector /metrics
      - 9090   # prometheus
      - 3000   # grafana
      - 16686  # jaeger UI
      - 3100   # tempo API

  tasks:
    - name: pacchetti di base
      dnf:
        name:
          - podman
          - python3
          - python3-pip
          - curl
          - firewalld
        state: present
        update_cache: true

    - name: SELinux (runtime)
      command: setenforce 0
      register: selinux_perm
      failed_when: selinux_perm.rc not in [0,1]
      changed_when: selinux_perm.rc == 0

    - name: SELinux (persist)
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'

    - name: firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - name: firewall 
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      loop: "{{ open_ports }}"

    - name: Installo podman-compose via pip 
      pip:
        name: podman-compose
        executable: pip3

    
   
    # -------------------------------------------------------------------------------
    - name: ESEGUI
      debug:
        msg:
          - "Ambiente pronto. Avvio manuale dello stack:"
          - "1) vagrant ssh"
          - "2) cd otel-lab/compose"
          - "3) podman-compose build"
          - "4) podman-compose up -d
                selezionare docker.io/prom/prometheus:v2.54.1"
          - " curl http://localhost:5000/ ; curl http://localhost:9464/metrics ; apri http://localhost:9090 e http://localhost:3000"
