Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.box_version = "4.2.16"
  config.vm.hostname = "otel-vm"

  
  config.vm.synced_folder "/Users/valentinlisci/Desktop/formazione_sou/otel-lab",
                          "/home/vagrant/otel-lab",
                          type: "virtualbox"


  config.vm.network "forwarded_port", guest: 5000, host: 5000   # App Flask
  config.vm.network "forwarded_port", guest: 9464, host: 9464   # Collector /metrics
  config.vm.network "forwarded_port", guest: 9090, host: 9090   # Prometheus
  config.vm.network "forwarded_port", guest: 3000, host: 3000   # Grafana
  config.vm.network "forwarded_port", guest: 16686, host: 16686, auto_correct: true # Jaeger 


  config.vm.provider "virtualbox" do |vb|
    vb.name = "otel-lab-vm"
    vb.memory = 2048
    vb.cpus = 2
  end

  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./provisioning/playbook.yml"
  end
end
