- name: Genera Dockerfile da template
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Crea Dockerfile da template
      template:
        src: Dockerfile.j2
        dest: ./Dockerfile


