Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=664"]

  config.vm.network "private_network", ip: "192.168.10.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "rocky9-ansible"
    vb.memory = 2048
    vb.cpus = 2
  end

  
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    
    if ! id "user" &>/dev/null; then
      useradd -m -s /bin/bash user
      echo "user:user" | chpasswd
    fi

    
    echo 'user ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/99_user
    chmod 440 /etc/sudoers.d/99_user

    
  SHELL

  
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
    ansible.verbose = "v"
  end
end
